modLoader="javafml"
loaderVersion="[40,)"
license="GPLv3"
issueTrackerURL="https://github.com/a1qs/vaultadditions/issues"

[[mods]]
modId="vaultadditions"
version="${file.jarVersion}"
displayName="Vault Additions"
displayURL="https://github.com/a1qs/vaultadditions"
logoFile="vaultadditions.png"
authors="a1qs"
description='''
This mod is a mod designed to work with Vault Hunters 3rd edition,
It adds a variety of features, which can be seen documented on the github page of this project.
'''

[[dependencies.vaultadditions]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vaultadditions]]
    modId="the_vault"
    mandatory=true
    versionRange="[1.18.2-3.15.1.3298,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vaultadditions]]
modId="woldsvaults"
mandatory=true
versionRange="[0.15.2,)"
ordering="NONE"
side="BOTH"